@endpoint = https://92p6m8c7ph.execute-api.us-west-2.amazonaws.com/prod

GET {{endpoint}}/hello/
###

GET {{endpoint}}/spaces/
###

GET {{endpoint}}/spaces?spaceId=1b870f80-1bf3-4f87-926d-f40640ed7f63
###

PUT {{endpoint}}/spaces?spaceId=1b870f80-1bf3-4f87-926d-f40640ed7f63
Content-Type: application/json

{
    "location": "Updated Location",
    "name": "Updated Best Location"
}
###

GET {{endpoint}}/spaces?location=London
###

POST {{endpoint}}/spaces/
Content-Type: application/json

{
    "location": "Mars",
    "name": "The Red Planet"
}
###

DELETE {{endpoint}}/spaces?spaceId=1b870f80-1bf3-4f87-926d-f40640ed7f63
###