@endpoint = https://92p6m8c7ph.execute-api.us-west-2.amazonaws.com/prod

GET {{endpoint}}/hello/
###

POST {{endpoint}}/spaces/
Content-Type: application/json

{
    "location": "London",
    "name": "Best Location"
}
###